changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature
        - add
    - title: 🐛 Bug Fixes
      labels:
        - fix
    - title: 🛠 Maintenance
      labels:
        - chore
        - refactor
    - title: 🏷 Others
      labels:
        - "*"